clusterAgent:
  log:
    encoding: json
    level: info
  image:
    name: ghcr.io/kube-tarian/tarian-cluster-agent
    # empty = default to app version
    tag:
  serverAddress: tarian-server:80
  service:
    type: ClusterIP
    nodeport:
  enableAddConstraint: false
nodeAgent:
  log:
    encoding: json
    level: info
  image:
    name: ghcr.io/kube-tarian/tarian-node-agent
    # empty = default to app version
    tag:
  clusterAgentAddress: tarian-server:80
  hostProcDir: /proc
webhook:
  failurePolicy: Ignore
  podAgentContainerImage:
    name: ghcr.io/kube-tarian/tarian-pod-agent
    # empty = default to app version
    tag:
