apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: {{ .Release.Name }}
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: {{ .Release.Name }}-controller-manager
      namespace: {{ .Release.Namespace }}
      path: /inject-pod-agent
  failurePolicy: {{ .Values.webhook.failurePolicy }}
  name: {{ .Release.Name }}.k8s.tarian.dev
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - pods
  sideEffects: None