apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  ports:
  - port: 80
    targetPort: 50052
{{- if .Values.clusterAgent.service.nodePort }}
    nodePort: {{ .Values.clusterAgent.service.nodePort }}
{{- end }}
    name: grpc
  - port: 8088
    targetPort: 8088
    name: falco
  selector:
    app: {{ .Release.Name }}
  type: {{ .Values.clusterAgent.service.type }}