apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  ports:
  - port: 80
    targetPort: 50051
{{- if .Values.server.service.nodePort }}
    nodePort: {{ .Values.server.service.nodePort }}
{{- end }}
    name: grpc
  selector:
    app: {{ .Release.Name }}
  type: {{ .Values.server.service.type }}